image: mingc/android-build-box:1.7.0

variables:
    GIT_SUBMODULE_STRATEGY: "recursive"
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - export MAVEN_HOME=`pwd`/kt-bindings

build:
    stage: build
    script: ./gradlew --parallel build check publishToMavenLocal publish -Dmaven.repo.local="$MAVEN_HOME"
    artifacts:
        paths:
            - kt-bindings
