image: gradle:alpine

variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - export MAVEN_HOME=`pwd`/web-kt-bindings

build:
    stage: build
    script: gradle --parallel build check publishToMavenLocal bintrayUpload -Dmaven.repo.local="$MAVEN_HOME"
    artifacts:
        paths:
            - web-kt-bindings
